[build]
  publish = "."
  command = ""
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../backend/"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://shopee-backend-jrbl.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.shopee.com.br https://shopee-backend-jrbl.onrender.com; img-src 'self' https://*.shopee.com.br https://via.placeholder.com data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[dev]
  framework = "#static"
  targetPort = 8080

[functions]
  directory = "functions"
  node_bundler = "esbuild"